Hospital/Hospital-war/src/java/ctrl/mb/DashboardController.java
package ctrl.mb;

import ctrl.rep.interfaces.*;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.Dependent;

@Named(value = "dashboardController")
@Dependent
public class DashboardController {

    @EJB
    private IEmployeeRep ie;
    @EJB
    private IPatientRep ip;
    @EJB
    private IMedicineRep im;
    @EJB
    private IMedicalReportRep imr;
    @EJB
    private IAppointmentRep ia;

    public DashboardController() {
    }

    public int getCountDoctor() {
        return ie.countDoctor();
    }

    public int getCountStaff() {
        return ie.countStaff();
    }

    public int getCountPatient() {
        return ip.count();
    }

    public int getCountMedicine() {
        return im.count();
    }

    public int getCountMedicalReport() {
        return imr.count();
    }

    public int getCountAppointmentWaiting() {
        return ia.countAppointmentWaiting();
    }

    public int getCountAppointmentFinish() {
        return ia.countAppointmentFinish();
    }

    public String prepareList() {
        return "Index?faces-redirect=true";
    }
}

Hospital/Hospital-war/src/java/ctrl/mb/EmployeeController.java
package ctrl.mb;

import ctrl.mb.util.JsfUtil;
import ctrl.rep.interfaces.IEmployeeRep;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.ejb.EJB;
import model.entities.Employees;

@Named(value = "employeeController")
@SessionScoped
public class EmployeeController implements Serializable {

    @EJB
    private IEmployeeRep ie;
    private Employees current;
    
    public EmployeeController() {
    }

    public Employees getEmployee() {
        if (current == null) {
            current = new Employees();
        }
        return current;
    }

    public void setEmployee(Employees admin) {
        this.current = admin;
    }

//<editor-fold defaultstate="collapsed" desc="Public Method">
    public String login() {
        Employees resultLogin = ie.checklog(current);
        if (resultLogin == null) {
            JsfUtil.addErrorMessage("Unknown login, try again");
            current = new Employees();
            return null;
        } else {
            current = resultLogin;
            JsfUtil.addSession("employee", current);
            return "Index?faces-redirect=true";
        }
    }

    public String logout() {
        return "Login.xhtml";
    }

    public void removSession() {
        JsfUtil.addSession("employee", null);
    }
//</editor-fold>
}

Hospital/Hospital-war/src/java/ctrl/mb/RoomMB.java
package ctrl.mb;

import ctrl.mb.util.JsfUtil;
import ctrl.rep.interfaces.*;
import java.util.*;
import javax.ejb.EJB;
import javax.faces.bean.*;
import javax.faces.model.*;

import model.entities.*;

@ManagedBean
@SessionScoped
public class RoomMB {

//<editor-fold defaultstate="collapsed" desc="Field">
    @EJB
    private IRoomRep ir;
    @EJB
    private IDepartmentRep id;
    private Room current;
    private RoomPK currentPK;
    private DataModel<Room> items = null;
    private int selectedItemIndex;
    private boolean isCreate;

    public boolean isIsCreate() {
        return isCreate;
    }

    public void setIsCreate(boolean isCreate) {
        this.isCreate = isCreate;
    }

//</editor-fold>
    public RoomMB() {
    }

//<editor-fold defaultstate="collapsed" desc="Private Method">
    // Cái này em dùng như vầy là để lúc a copy qua thằng khác chỉ cần sửa cái return, mấy hàm phía dưới ko bị ảnh hưởng
    private IRoomRep getAction() {
        return ir;
    }

    // Tạo Model
    private DataModel createModel() {
        return new ListDataModel(getAction().findAll());
    }

    // Gọi hàm này thì items = null mà ở page jsf gọi thằng getItems() thằng này sẽ check if null thì khởi tạo.
    private void recreateModel() {
        items = null;
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Public Method">
    public List<Room> getAll(){
        return getAction().findAll();
    }
    
    public DataModel getItems() {
        if (items == null) {
            items = createModel();
        }
        return items;
    }

    public Room getByID(Object id) {
        return getAction().find(id);
    }

    public Room getSelected() {
        if (current == null) {
            current = new Room();
            currentPK = new RoomPK();
            current.setRoomPK(currentPK);
            selectedItemIndex = -1;
        }
        return current;
    }

    public String prepareList() {
        recreateModel();
        return "Room?faces-redirect=true";
    }

    public String prepareCreate() {
        current = new Room();
        currentPK = new RoomPK();
        isCreate = true;
        current.setRoomPK(currentPK);
        return "RoomForm";
    }

    public String prepareEdit(Object id) {
        current = getByID(id);
        currentPK = getByID(id).getRoomPK();
        isCreate = false;
        return "RoomForm";
    }

    public String create() {
        try {
            current.setRoomPK(currentPK);
            current.setDepartment(id.find(current.getRoomPK().getDepartmentID()));
            getAction().create(current);
            JsfUtil.addSuccessMessage("Thêm thành công");
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, "Thêm thất bại");
            return null;
        }
    }

    public String update() {
        try {
            getAction().edit(current);
            current.setDepartment(id.find(current.getRoomPK().getDepartmentID()));
            JsfUtil.addSuccessMessage("Cập nhật thành công");
            return prepareEdit(current.getRoomPK());
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, "Cập nhật thất bại");
            return null;
        }
    }

    public Collection<Department> getRefDepartment() {
        return id.findAll();
    }  
//</editor-fold>
}

Hospital/Hospital-war/web/admin/DepartmentForm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="../templates/_AdminPage.xhtml">
        <!-- Header -->
        <ui:define name="head">
            <title>Form Department</title>
        </ui:define>

        <!-- Body -->
        <ui:define name="body">   
            <!-- page title area start -->
            <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6 my-4">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Department</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="Index.xhtml">Home</a></li>
                                <li><span>Department</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->

            <!-- page content start -->
            <div class="container-fluid">
                <!--Form-->
                <div class="card-body">
                    <ui:include src="share/message.xhtml" /> 
                    <div class="form">
                        <div class="form-group">
                            <h:outputLabel value="Department Name" for="departmentName" />
                            <h:inputText id="departmentName" 
                                         value="#{departmentMB.selected.name}" 
                                         title="Department Name" 
                                         required="true" 
                                         class="form-control"
                                         />
                        </div>

                            <div class="form-group">
                                <h:outputLabel value="Type Department" for="departmentType" />
                                <h:selectOneMenu id="departmentType" 
                                                 value="#{departmentMB.selected.isDoctor}" 
                                                 title="Department Type" 
                                                 required="true" 
                                                 class="form-control"
                                                 >
                                    <f:selectItem itemValue = "true" itemLabel = "MEDICAL" /> 
                                    <f:selectItem itemValue = "false" itemLabel = "NON MEDICAL" />
                                </h:selectOneMenu>
                            </div>

                        <div class="formAction">
                            <h:commandLink action="#{departmentMB.create}" 
                                           value="Thêm mới"
                                           rendered="#{departmentMB.isCreate}"
                                           class="far fa-check-circle btn btn-outline-primary mr-3"
                                           />

                            <h:commandLink action="#{departmentMB.update}" 
                                           value="Cập nhật"
                                           rendered="#{!departmentMB.isCreate}"
                                           class="far fa-check-circle btn btn-outline-primary mr-3"
                                           />

                        </div>
                    </div>
                </div>
                <!--End Form-->
            </div>
            <!-- page content end -->

        </ui:define>
    </ui:composition> 
</html>

Hospital/Hospital-war/web/admin/Index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="../templates/_AdminPage.xhtml">
        <!-- Header -->
        <ui:define name="head">
            <title>Index</title>
        </ui:define>

        <!-- Body -->
        <ui:define name="body">   
            <!-- page title area start -->
            <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6 my-4">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Dashboard</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="index.html">Home</a></li>
                                <li><span>Dashboard</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->

            <!-- page content start -->
            <div class="container-fluid">
                <!-- seo fact area start -->
                <div class="row">
                    <div class="col-md-4 mt-5 mb-3">
                        <div class="card">
                            <div class="seo-fact sbg1">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon font-weight-bold"><i class="fas fa-user-injured"></i> Patient</div>
                                    <h2>#{dashboardController.countPatient}</h2>
                                </div>
                                <canvas id="seolinePatient" height="50"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 mt-md-5 mb-3">
                        <div class="card">
                            <div class="seo-fact sbg2">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon font-weight-bold"><i class="fas fa-user-md"></i> Doctor</div>
                                    <h2>#{dashboardController.countDoctor}</h2>
                                </div>
                                <canvas id="seolineDoctor" height="50"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 mt-md-5 mb-3">
                        <div class="card">
                            <div class="seo-fact sbg4">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon font-weight-bold"><i class="fas fa-user-tie"></i> Staff</div>
                                    <h2>#{dashboardController.countStaff}</h2>
                                </div>
                                <canvas id="seolineStaff" height="50"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 mb-3 mb-lg-0">
                        <div class="card">
                            <div class="seo-fact bg-success">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon"><i class="fas fa-pills"></i> Medicine</div>
                                    <h2>#{dashboardController.countMedicine}</h2>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 mb-3 mb-lg-0">
                        <div class="card">
                            <div class="seo-fact bg-warning">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon"><i class="fas fa-notes-medical"></i> Medical Report</div>
                                    <h2>#{dashboardController.countMedicalReport}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 mb-3 mb-lg-0">
                        <div class="card">
                            <div class="seo-fact bg-dark">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon"><i class="fas fa-calendar-alt"></i> Waiting</div>
                                    <h2>#{dashboardController.countAppointmentWaiting}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 mb-3 mb-lg-0">
                        <div class="card">
                            <div class="seo-fact bg-danger">
                                <div class="p-4 d-flex justify-content-between align-items-center">
                                    <div class="seofct-icon"><i class="fas fa-calendar-check"></i> Finished</div>
                                    <h2>#{dashboardController.countAppointmentFinish}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- page content end -->            
        </ui:define>
        <script>
                alert("hello");
        </script>
    </ui:composition> 
</html>

Hospital/Hospital-war/web/admin/MedicalReportForm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="../templates/_AdminPage.xhtml">
        <!-- Header -->
        <ui:define name="head">
            <title>Index</title>
        </ui:define>

        <!-- Body -->
        <ui:define name="body">   
            <!-- page title area start -->
            <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6 my-4">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Medical Report</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="Index.xhtml">Home</a></li>
                                <li><span>Medical Report</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid">
                <!--Form-->
                <div class="card-body">
                    <ui:include src="share/message.xhtml" />                     
                    <div class="form">
                        <div class="form-row">
                            <div class="form-group col">
                                <h:outputLabel value="Medical Report No" for="medicalReportNo" />
                                <h:inputText id="medicalReportNo" 
                                             value="#{medicalReportMB.selected.reportID}" 
                                             title="Medical Report No" 
                                             required="true" 
                                             class="form-control"
                                             />
                            </div>
                            <div class="form-group col">
                                <h:outputLabel value="Department ID" for="departmentId" />
                                <h:inputText id="departmentId" 
                                             readonly="true"
                                             value="#{medicalReportMB.selected.pati}" 
                                             title="Department Id" 
                                             required="true" 
                                             class="form-control"
                                             />
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <h:outputLabel value="Medical Report Type" for="medicalReportType" />
                                <h:selectOneMenu id="medicalReportType" 
                                                 value="#{medicalReportMB.selected.type}" 
                                                 title="Medical Report Type" 
                                                 required="true" 
                                                 class="form-control"
                                                 >
                                    <f:selectItem itemValue = "false" itemLabel = "Normal" />
                                    <f:selectItem itemValue = "true" itemLabel = "Service" />
                                </h:selectOneMenu>
                            </div>   
                            <div class="form-group col">
                                <h:outputLabel value="Department" for="Department" />
                                <h:selectOneMenu id="Department" 
                                                 value="#{medicalReportMB.selected.medicalReportPK.departmentID}" 
                                                 title="Department" 
                                                 required="true" 
                                                 class="form-control"
                                                 >
                                    <f:selectItems value = "#{medicalReportMB.refDepartment}" 
                                                   var="dp" 
                                                   itemLabel="#{dp.name}" 
                                                   itemValue="#{dp.departmentID}"                                                      
                                                   />
                                </h:selectOneMenu>
                            </div> 
                        </div>


                        <div class="form-group">
                            <h:outputLabel value="Description" for="medicalReportDescription" />
                            <h:inputTextarea id="medicalReportDescription" 
                                             value="#{medicalReportMB.selected.description}" 
                                             title="Medical Report Description" 
                                             required="true" 
                                             class="form-control"
                                             />
                        </div>

                        <div class="formAction">
                            <h:commandLink action="#{medicalReportMB.create}" 
                                           value=" Thêm mới"
                                           rendered="#{medicalReportMB.isCreate}"
                                           class="far fa-check-circle btn btn-outline-primary mr-3"
                                           />

                            <h:commandLink action="#{medicalReportMB.update}" 
                                           value=" Cập nhật"
                                           rendered="#{!medicalReportMB.isCreate}"
                                           class="far fa-check-circle btn btn-outline-primary mr-3"
                                           />

                            <h:commandLink action="#{medicalReportMB.prepareList}" 
                                           value=" Back to List" 
                                           immediate="true"
                                           class="far fa-arrow-alt-circle-left btn btn-outline-dark"
                                           />
                        </div>
                    </div>
                </div>
                <!--End Form-->
            </div>
            <!-- page content end -->

        </ui:define>
    </ui:composition> 
</html>

Hospital/Hospital-war/web/admin/RoomForm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="../templates/_AdminPage.xhtml">
        <!-- Header -->
        <ui:define name="head">
            <title>Index</title>
        </ui:define>

        <!-- Body -->
        <ui:define name="body">   
            <!-- page title area start -->
            <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6 my-4">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Room</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="Index.xhtml">Home</a></li>
                                <li><span>Room</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid">
                <!--Form-->
                <div class="card-body">
                    <ui:include src="share/message.xhtml" />                     
                    <div class="form">
                        <div class="form-row">
                            <div class="form-group col">
                                <h:outputLabel value="Room No" for="roomNo" />
                                <h:inputText id="roomNo" 
                                             value="#{roomMB.selected.roomPK.roomNo}" 
                                             title="Room No" 
                                             required="true" 
                                             class="form-control"
                                             />
                            </div>
                            <div class="form-group col">
                                <h:outputLabel value="Department ID" for="departmentId" />
                                <h:inputText id="departmentId" 
                                             readonly="true"
                                             value="#{roomMB.selected.roomPK.departmentID}" 
                                             title="Department Id" 
                                             required="true" 
                                             class="form-control"
                                             />
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <h:outputLabel value="Room Type" for="roomType" />
                                <h:selectOneMenu id="roomType" 
                                                 value="#{roomMB.selected.type}" 
                                                 title="Room Type" 
                                                 required="true" 
                                                 class="form-control"
                                                 >
                                    <f:selectItem itemValue = "false" itemLabel = "Normal" />
                                    <f:selectItem itemValue = "true" itemLabel = "Service" />
                                </h:selectOneMenu>
                            </div>   
                            <div class="form-group col">
                                <h:outputLabel value="Department" for="Department" />
                                <h:selectOneMenu id="Department" 
                                                 value="#{roomMB.selected.roomPK.departmentID}" 
                                                 title="Department" 
                                                 required="true" 
                                                 class="form-control"
                                                 >
                                    <f:selectItems value = "#{roomMB.refDepartment}" 
                                                   var="dp" 
                                                   itemLabel="#{dp.name}" 
                                                   itemValue="#{dp.departmentID}"                                                      
                                                   />
                                </h:selectOneMenu>
                            </div> 
                        </div>


                        <div class="form-group">
                            <h:outputLabel value="Description" for="roomDescription" />
                            <h:inputTextarea id="roomDescription" 
                                             value="#{roomMB.selected.description}" 
                                             title="Room Description" 
                                             required="true" 
                                             class="form-control"
                                             />
                        </div>

                        <div class="formAction">
                            <h:commandLink action="#{roomMB.create}" 
                                           value=" Thêm mới"
                                           rendered="#{roomMB.isCreate}"
                                           class="far fa-check-circle btn btn-outline-primary mr-3"
                                           />

                            <h:commandLink action="#{roomMB.update}" 
                                           value=" Cập nhật"
                                           rendered="#{!roomMB.isCreate}"
                                           class="far fa-check-circle btn btn-outline-primary mr-3"
                                           />

                            <h:commandLink action="#{roomMB.prepareList}" 
                                           value=" Back to List" 
                                           immediate="true"
                                           class="far fa-arrow-alt-circle-left btn btn-outline-dark"
                                           />
                        </div>
                    </div>
                </div>
                <!--End Form-->
            </div>
            <!-- page content end -->

        </ui:define>
    </ui:composition> 
</html>